title: ""
description: ""
theme: jekyll-theme-cayman
collections:
  tools:
    output: true
    permalink: /:collection/:name
  tutorials:
    output: true
    permalink: /:collection/:name
  examples:
    output: true
    permalink: /:collection/:name
defaults:
 - scope:
     path: ""
   values:
     layout: "default"
 - scope:
     path: ""
     type: "tools"
   values:
     layout: "tools"
 - scope:
     path: ""
     type: "tutorials"
   values:
     layout: "tutorials"
 - scope:
     path: ""
     type: "examples"
   values:
     layout: "examples"
